### ISSUE TITLE
Line Number Offset Doesn't Work In v. 3.6?

### ISSUE THREAD

**Issue by linux4me** [EnlighterJS/Plugin.WordPress#103]
I'm using WP 4.9.6 and EnlighterJS v. 3.6 on a clean test install with no other plugins installed, and the Twenty Seventeen theme. I haven't been able to get line number offsets to work.

## Steps to Reproduce the Problem

1. Create a new post using the visual editor.
2. Click the Enlighter Code Insert icon.
3. Select HTML for the language.
4. Paste the following into the Insert form: `<div class="site-inner">`
5. Click the inserted code to select it, then click the Enlighter Code Settings icon for the inserted code.
6. Set the Linenumber offset to any number greater than 1.
7. Click OK.
8. Update and view the post. The line number will remain 1 on the front end, and if you check the Enlighter Code Settings for the entry, the Linenumber offset isn't saved.

## Expected Behavior
The linenumber offset should set the line number to whatever has been set in the Enlighter Code Settings dialog box. I've tried getting the Linenumber offset to work with a multi-line code snippet, and it doesn't work in that case, either.

**Comment by AndiDittrich** [comment]
Hi @linux4me ,

thanks for your report. the whole "change settings" dialog (via code block button) was broken in the recent TinyMCE version. the settings button on the editor toolbar still works!
 see #101 - the options itself are note affected.

the issue has been fixed in ([EnlighterJS.TinyMCE](https://github.com/EnlighterJS/Plugin.TinyMCE)) **v3.4.0** - added to Enlighter WordPress Plugin **v3.7-BETA3**. you can use the latest beta version (master branch) from GitHub

best regards, Andi

**Comment by linux4me** [comment]
I just updated to v. 3.7 of Enlighter, and it's fixed! Thank you!
