### ISSUE TITLE
TinyMCE: Enlighter footer label collides with content

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [EnlighterJS/Plugin.WordPress#120]
I was hiding it with CSS, but I updated the plugin today and it is appearing again. Really I think it has zero utility in the best case, in the worse case, it is over the text...

![image](https://user-images.githubusercontent.com/7463564/45705906-228f7a80-bb7b-11e8-8bb6-34d7204fd4da.png)

**Comment by AndiDittrich** [comment]
Hi @JavierSegoviaCordoba 

thanks for your report. the `padding-bottom` value will be modified in the next release to add some space between the last line and the Enlighter slogan.

generally the slogan was introduced by a [feature request](https://wordpress.org/support/topic/remove-branding-on-toolbar/) because some users experienced usability issues with there (non professional) users which were confused about the old window naming scheme "Enlighter: <language>". therefore i've moved the Enlighter label from the title to the footer. 

on the other hand it is necessary to "mark" the codeblocks generated by Enlighter to show users that the "block" does not belong to their inserted editor content/design.

best regards, Andi

**Comment by AndiDittrich** [comment]
it has been fixed in EnlighterJS/Plugin.TinyMCE [v3.5.1](https://github.com/EnlighterJS/Plugin.TinyMCE/tree/v3.5.1)

you can take the files from `Plugin.TinyMCE/dist` directory and upload them into `wp-content/plugins/enlighter/resources/editor` to apply the changes immediately

**Comment by AndiDittrich** [comment]
TinyMCE release is now available within the Enlighter Plugin master branch
