### ISSUE TITLE
Editing Existing Block with WordPress Code Editor (CodeMirror)

### ISSUE THREAD

**Issue by markolbert** [EnlighterJS/Plugin.WordPress#121]
I'm able to insert enlighter code blocks in WordPress posts (classic editor; not gutenberg). But I can't edit them in the Visual Code Editor. How do I bring up the Visual Code Editor for an existing enlighter code block?

**Comment by AndiDittrich** [comment]
hi @markolbert ,

that's not normal. after adding a codeblock you can edit the content directly within the visual editor.

does the demo page work for you ? https://tinymce.enlighterjs.org/

**Comment by markolbert** [comment]
Hi Andi (and thanx for the amazingly quick reply :)). Yes, that demo link works fine. I should've put a screenshot of what I'm seeing when I try to edit the page:

![untitled-1](https://user-images.githubusercontent.com/9095610/45766530-ae8dba80-bbec-11e8-935e-9318092464b1.png)

I've noticed that there's no link showing in the TinyMCE toolbar to open the Visual Editor, just a link to insert a code block or change code block settings. I checked the TinyMCE settings, but couldn't find anything.

**Comment by AndiDittrich** [comment]
hmmm your screenshot looks fine. there are not more buttons available in the toolbar (like the demo) - what did you expect ?

**Comment by markolbert** [comment]
Ah! I may not have described the issue correctly...

Can that code block -- the one framed by the black bar labeled "Enlighter: JSON" -- be edited in the Visual Editor? Or do I just edit it "in place"? I was thinking there should be a button that, when, say, the cursor was inside the code block, would launch the Visual Editor to display the code block and allow it to be changed in the Editor. But maybe that's not how the plugin works.

**Comment by AndiDittrich** [comment]
well...in the WordPress terminology "Visual Editor" is the official name of their TinyMCE integration - therefore i was confused about your question, but now i know what you mean.

**the short answer is no**

--------------------

**the long answer..**

* Enlighter is designed to be as closed on the WordPress UI / usability as possible
* EnlighterJS is designed as syntax highlighter not as IDE
* The new ace/cloud9 based "code editor" on WordPress is not used by Enlighter because the highlighting differ from that created by Enlighter and this will confuse user (of course it is technical possible..)
* An IDE like code editor is **IMHO** not necessary to post sourcecode. the "standard" workflow consist of a copy+paste action between your IDEs and WordPress...you didn't want do edit sourcecode within the editor (missing linting, autocomplete)
* Finally, i want to keep the editing features as simple as possible


best regards, Andi

**Comment by markolbert** [comment]
That makes sense, thanx for the explanation. FWIW, I'm not trying to use it like an IDE; I was mostly wondering how I handle situations where I want to change the "target" language. It sounds like the best way to do that is simply to edit the <pre> tag directly. I just thought there might be a way to do it through the visual editor.

**Comment by AndiDittrich** [comment]
to change the language/change the settings you have to focus into the codeblock. an icon will appear on the upper right corner (as well as the settings icon in the toolbar) - this allows you to change the codeblock settings. the editing of the text itself is limited to the editor pane

**Comment by AndiDittrich** [comment]
![enlighterjs-tinymce](https://user-images.githubusercontent.com/1474107/45835148-88aa0800-bd09-11e8-88ae-53c0b86ac860.gif)

**Comment by AndiDittrich** [comment]
https://github.com/EnlighterJS/Plugin.WordPress/blob/master/docs/Usage_VisualEditor.md#change-code-settings--advanced-code-settings

**Comment by markolbert** [comment]
Thanx for pointing that out. I missed that I could change the language through the settings popup.

And, more importantly, thanx for creating and maintaining a cool addin!
