### ISSUE TITLE
Enable Enlighter on post type only

### ISSUE THREAD

**Issue by rafaelcmgt** [EnlighterJS/Plugin.WordPress#124]
Hello;

I am trying to enable Enlighter only on my blog and a custom post type called "snippet". I am using the enlighter_startup filter this way:

```php
function rmw_desactivar_enlighter($enabled){
  if (is_singular( array( 'post', 'snippet') ) ) {
    return true;
  } else {
    return false;
  }
}
// add startup filter
add_filter('enlighter_startup', 'rmw_desactivar_enlighter');
```

However, with this code, Enlighter is disabled on my whole site. "is_singular" is not working, I think. 

Is there a way to achieve this? Am I using the enlighter_startup filter improperly?

Thank you.

**Comment by AndiDittrich** [comment]
Hi @rafaelcmgt ,

the WordPress [is_singular](https://codex.wordpress.org/Function_Reference/is_singular) function is targeted to be used inside `the loop` / in templates.

the `enlighter_startup` filter is executed on an earlier stage - on [init](https://codex.wordpress.org/Plugin_API/Action_Reference/init) - therefore it won't work because the wp_query object has not been initialized yet.

whats your use case / why do you want to limit Enlighter to a single post type ? maybe there are other solutions

best regards, Andi

**Comment by rafaelcmgt** [comment]
Hi,

Enlighter is causing issues with a 3rd party plugin I am using in 1 page only (the page where this 3rd party plugin is working). I am using Enlighter only in post and snippet CPT. Enlighter JS is being queueing on the whole site. This is why I decided to enable Enlighter only on posts and snippet CPT.

I know that I can disable Enlighter on selected page by URL and this would solve the issues I have (Actually, I tried and it was working properly). But I thought: if I enable Enlighter only where I am going to use it, 1 script less to load for the rest of the site.

**Comment by AndiDittrich** [comment]
try Dynamic Resource Invocation (DRI)  `Enlighter -> BETA -> Dynamic Resource Invocation`

**Comment by AndiDittrich** [comment]
or you can just dequeue the EnlighterJS resources - this should work with `is_singular` calls

**Comment by rafaelcmgt** [comment]
Thanks,

DRI doesn't work and there are a lot of resources to dequeue (actually, I don't know how to dequeue some of them). So I  have decided to use enlighter_startup filter to disable Enlighter on selected page by URL.

**Comment by AndiDittrich** [comment]
ok great. you can just copy+paste the [dequeue code](https://github.com/EnlighterJS/Plugin.WordPress/blob/master/class/ResourceLoader.php#L236)
