### ISSUE TITLE
Conflict with Divi's Visual Builder

### ISSUE THREAD

**Issue by yankiara** [EnlighterJS/Plugin.WordPress#130]
Hi!!!
And first, thanks for this awesome plugin :-)

I have an issue though. When your plugin is active and I try to edit any page with Divi's Visual Builder, the  builder crashes. I reported the problem to Elegant Theme support, and here's their response:

--------------------------------------------------------------------------
The issue related to external library that this plugin is loading:
https://ajax.googleapis.com/ajax/libs/mootools/1.6.0/mootools.min.js

![enlighter and divi builder conflict](https://user-images.githubusercontent.com/36680757/48098738-d88f5080-e21d-11e8-932b-7794fb3a7fa5.png)
Please contact the plugin developers and ask them to check the issue, if it possbile the can disable this library only for the Visual Builder using the following PHP functions:
et_core_is_fb_enabled() || isset( $_GET['et_fb'] )

-----------------------------------------------------------------------------

Could you investigate this, please?

Thanks in advance, and have a beautiful day.
Yan.

**Comment by AndiDittrich** [comment]
Hi @yankiara ,

thanks for your report. the issue is caused by the MooTools javascript framework which is still used by EnlighterJS v2 to highlight the code. This issue **cannot be fixed in the current release**

The next major release of the WordPress Plugin (v4) which will contain the new EnlighterJS v3 release will work without MooTools!

Generally you could add a small piece of code to your `functions.php` file which dequeues MooTools in case your "Visual Builder" is active. I can provide this small snippet based on the condition `et_core_is_fb_enabled() || isset( $_GET['et_fb'] )` - this will disable the highlighting (but not the editor integration) in case the page builder is active.

best regards, Andi

**Comment by yankiara** [comment]
Hi, and thanks for your quick reply :-)
I tried this and it works:
```
function pavenum_remove_mootools_with_visual_builder() {
	if ( et_core_is_fb_enabled() || isset( $_GET['et_fb'] ) ) {
		wp_dequeue_script( 'mootools-google-cdn' );
	}
}
add_action('wp_footer', 'pavenum_remove_mootools_with_visual_builder');
```
I guess I can close the issue. Can't wait for v4!!!

Thanks again for this great pluign; it just rocks!!
Yan.
