### ISSUE TITLE
Where is the toolbar in Wordpress 5.0?

### ISSUE THREAD

**Issue by matcharles** [EnlighterJS/Plugin.WordPress#137]
I'm really sorry to open up a ticket about this as it may not even pertain to this plugin, but I can't find the enlighter button in the toolbar since I updated Wordpress to 5.0. Anything I need to toggle? Thanks a lot!

**Comment by AndiDittrich** [comment]
Hi @matcharles ,

it depends on the Editor you're using:

* **Gutenberg Editor with Enlighter Blocks**
  The [Enlighter Gutenberg Plugin](https://github.com/EnlighterJS/Plugin.Gutenberg) is still in beta phase and is disabled by default. it has to be enabled in `Enlighter -> BETA -> Gutenberg Editor` - but there won't be any kind of buttons because Gutenberg doesn't work this way
* **Gutenberg Editor with Classic Editor Blocks**
  The Visual Editor Plugin (buttons within toolbar) is enabled by default
* **Classic Editor Plugin (TinyMCE)**
  The Visual Editor Plugin (buttons within toolbar) is enabled by default

please take a look onto the  [editor tutorials](https://github.com/EnlighterJS/Plugin.WordPress/tree/master/docs) to see how its working :+1: 

best regards, Andi

**Comment by matcharles** [comment]
Thanks so much Andi, works like a charm! I had to enable the beta Gutenberg setting.

You can close this, appreciate the help very much. Happy Holidays!
