### ISSUE TITLE
Updating failed and no preview shown

### ISSUE THREAD

**Issue by mmajcica** [EnlighterJS/Plugin.WordPress#163]
I'm trying to using this plugin, however it is not working. Probably there are some settings that are not correct.

In case I add a block the and go for a preview, the following is what I get:

![image](https://user-images.githubusercontent.com/3026551/55147504-cec3a680-5146-11e9-9999-75061d9d4911.png)

By remove the block the preview shows correctly.

Any ideas on what could cause this behavior?

**Comment by AndiDittrich** [comment]
Hi @mmajcica ,

i've tried to reproduce your issue but everything is working as expected within the testing environment.
by clicking on the `preview` button, the Gutenberg Editor opens a new window. A modal message as shown above is only shown in case the post is saved/published (it normally appear green with `Post updated.View Post`)

whats your **exact** workflow (step-by-step) ?

did you tried to use Enlighter without **any other** WordPress plugins on your testing site ?

the issue is very strange because Enlighter **does not** hook into any save/publish action... the "block" is just a custom Gutenberg block using the API

best regards, Andi

**Comment by mmajcica** [comment]
Hi @AndiDittrich, indeed it has nothing to do with your plugin. Strangely enough, by just installing  CLASSIC EDITOR plugin, without activating it, solves the issue.
