### ISSUE TITLE
Proposal: Support <code>var1</code> tag vs `var1` tag

### ISSUE THREAD

**Issue by getglad** [EnlighterJS/Plugin.WordPress#175]
I've outline the problem here: https://wordpress.stackexchange.com/questions/342257/turn-off-gutenberg-auto-formatting-of-code-in-editing-experience

But, essentially, the Gutenburg paragraph block auto formats markdown-style back ticks for code snippets (ie \`var1\' ) into code tags (ie, < code> var1 < /code>), which makes for a monotonous chain of undoing and cursor re-positioning.

If Gutenburg is going to enforce this pattern, it would be helpful to have the plugin support the < code> var1 < /code> pattern

I know this has been addressed before from a different POV (https://github.com/EnlighterJS/Plugin.WordPress/issues/154), but interested to see if the detection approach can be changed so the < code> tag may be be inflated into the Enlighter element.

So long version short...

Instead of requiring in paragraph blocks: \`var1\`
Also support in paragraph blocks: < code> var1 < /code>

So in the front end, either format produces:

```
<span class="gitEnlighterJS EnlighterJS">
   <span class="">var1</span>
</span>
```

I would also argue this would make for a more "native" Gutenburg experience, as my paragraph block would now appear with the code tag decoration (ie, `var1`) vs having ticks in my text (ie, \`var1\`).

Happy to attempt some of the lift on this myself, but would need some pointers on where in the code base the detection/transformation is happening.

**Comment by AndiDittrich** [comment]
Hi @getglad ,

EnlighterJS and the Enlighter plugin already use `<code>` tags to highlight inline code - see enlighterjs.org and especially the TinyMCE plugin/integration.

Just change the css inline selector to `code` - but without a "full ui integration" it is impossible to set the language of the inline snippet.

Currently (as i know) there is no kind of hook/filter/action available to remove the backtick auto processing from Gutenberg or TinyMCE (same issue with code backticks..) and replace it with a custom version....it's caused by the React based monolithic design.

The next Enlighter.Gutenberg plugin release will include inline syntax highlighting similar to the TinyMCE plugin via a simple "text insert dialog"

**Comment by getglad** [comment]
So if I'm following you, change is...

Enlighter Plugin Screen -> Options -> Advance Options -> Default: code.EnlighterJSRAW -> Inline CSS Selector

Before: code.EnlighterJSRAW
After: code

Correct? If so... I feel a little dumb...

**Comment by AndiDittrich** [comment]
that is the correct way.

but keep in mind that you have to add the `data-enlighter-language` attribute manually - otherwise the inline code is highlighted with the default language (generic)
