### ISSUE TITLE
King Composer: Markdown + TinyMCE integration not working

### ISSUE THREAD

**Issue by JRCrawford** [EnlighterJS/Plugin.WordPress#176]
I have the following code: 
![image](https://user-images.githubusercontent.com/16747994/61091455-1e9a5500-a43a-11e9-871b-c85c45fac759.png) however when I view it on the website/frontend it appears like this: 
![image](https://user-images.githubusercontent.com/16747994/61091476-32de5200-a43a-11e9-8499-1b0b94947747.png)

Ideally the <br/> and other HTML tags should not be seen

**Comment by AndiDittrich** [comment]
Hi @JRCrawford ,

it looks like that Enlighter Markdown option has been disabled. Please check this.

in case it is still not working, please disable other caching/content plugins for testing.

**Comment by JRCrawford** [comment]
Hi @AndiDittrich 

Thanks for the reply :-) I did take a quick look but it seems that is all selected as seen below: 
![image](https://user-images.githubusercontent.com/16747994/61108912-82913d80-a47b-11e9-84a0-5ba76c3faf08.png)

Just to be sure, I even added the markdown option for the bbform, but that too didn't help.
![image](https://user-images.githubusercontent.com/16747994/61108979-a48ac000-a47b-11e9-80df-8ae23bc3acdf.png)

I currently am still setting up my site and as such I don't have any caching in place. 

I should point out that the "King Composer" plugin to type out the content (if that helps)

**Comment by AndiDittrich** [comment]
i'm a bit confused - the editor in your first post looks like the text/html mode of the "Classic Editor" (TinyMCE) - it doesn't look like a thrid party plugin like "King Composer"

does the Gutenberg or TinyMCE integration work as expected ?

**Comment by JRCrawford** [comment]
I thought it might be a bit more helpful to show a gif instead.  You can see it [over here.](https://i.imgur.com/vKyULBI.gif) 

Sadly the visual editor doesn't work as expected which is why I tried to do the embedded option instead

**Comment by AndiDittrich** [comment]
the issue seems to be related to "King Composer" - please ask their support for further assist.

in case you've enabled the classic editor integration, the Enlighter buttons should be appear within the "Text block edit" editor - if not the "King Composer" doesn't load any third party editing plugins - such issue cannot be addressed by Enlighter...sry

the Enlighter markdown filter uses the WordPress filter hook [the_content](https://codex.wordpress.org/Plugin_API/Filter_Reference/the_content) - in case your page builder plugin doesn't invoke this filter or apply some pre-processing of the content (output looks like wp-autop filter) the markdown integration cannot work.

**Comment by JRCrawford** [comment]
Thanks for the detailed reply. Very helpful.  I'll see what the KC guys think of it.
