### ISSUE TITLE
Crayon Compatibility Shell Language

### ISSUE THREAD

**Issue by gitsnow** [EnlighterJS/Plugin.WordPress#183]
Sorry to bother again, but I found that Crayon's language value for Shell is **"sh"** while you use **"shell"**.  I believe this was always a bug within Crayon as the highlighting never looked right.

In any case, this causes any pre with attribute **"lang:sh"** not to be highlighted properly.

I did a quick and dirty modification to the Crayon.php to change the language value from sh to shell.
```
if (isset($crayonAttributes['lang'])){
    if ($crayonAttributes['lang'] == "sh") {
        $crayonAttributes['lang'] = "shell";
    }
    $htmlAttributes['data-enlighter-language'] = InputFilter::filterLanguage($crayonAttributes['lang']);
}
```

**Comment by AndiDittrich** [comment]
Hi @gitsnow ,

thanks for your feedback.

this issue can be solved in two different ways:

1. add a language mapping to the `Crayon` compatibility mode
2. add a language alias to the existing language mapping of EnlighterJS

currently i would prefer the second option because `sh` might also be used by other users who want to highlight shell scripts.

**Comment by AndiDittrich** [comment]
i've added `sh` and `zsh` as additional language aliases for shell scripts

**Comment by gitsnow** [comment]
Thanks for all your hard work!
