### ISSUE TITLE
Kotlin Playground Support

### ISSUE THREAD

**Issue by mamatagelanee07** [EnlighterJS/Plugin.WordPress#186]
Are Kotlin snippets runnable? 
https://github.com/Kotlin/kotlin-playground-wp-plugin

If it's not available, Can we add support for Kotlin Interactive Playground?

Thanks!

**Comment by AndiDittrich** [comment]
HI @mamatagelanee07 ,

EnlighterJS is a pure syntax highlighter... not an online editor/ide like ACE which is used by most "playgrounds".

generally it is not possible to do such integration within the WordPress plugin because it just "marks" the codeblocks to be highlighted. 

Within EnlighterJS it is possible to add any kind of integrations (javascript) but this will blow up the code....and other people would also like to have a special integration.

sorry!
