### ISSUE TITLE
Allow $ instead of line number for terminal commands [FeatureRequest]

### ISSUE THREAD

**Issue by samjonester** [EnlighterJS/Plugin.WordPress#19]
There should be line number type. Then we can have $ instead of line number to signify terminal commands.

**Comment by AndiDittrich** [comment]
Well...it's more a philosophical question..

Generally line-numbers are implemented as ordered CSS lists... it should be possible to add a special function which will disable the standard line-numbering for `cli` commands and replace it with the dollar `$` sign.

but this will only work for single line commands... do you think it's reasonable to add this special exception instead of writing a dollar sign manually ?

on the other hand, a lot of tutorials are using terminal outputs. maybe it's a better solution to create a new "language" called `cli` which will **highlight** the complete output. in this case the dollar sign is not necessary because it's mostly included within the bash prompt. 
and some users may want to use line-numbering for large terminal outputs.

**Comment by samlawrencejones** [comment]
Good point. I was thinking that like the ordered list it would be an unordered list with a custom bullet. You're right that some users would still want the line numbering instead. I don't think the $ are necessary, but they do make it painfully obvious that the reader executes the command in the terminal. I like your idea of using a desperate language type. Then there could be syntax highlighting for things like ; & | and flags or options to a command.
