### ISSUE TITLE
add support to cornerstone

### ISSUE THREAD

**Issue by LIJE** [EnlighterJS/Plugin.WordPress#195]
Hi,

I'm using Cornerstone on all my projects and it seems your plugin breaks the pages built with it. Well, some of them for an unknown reason.

Plugin: https://theme.co/cornerstone/

Issue: https://www.lije-creative.com/portfolio/

Here is what the support from Themeco said to me: "It's not due to update but caused by a plugin, I went ahead and deactivated the Enlighter - Customizable Syntax Highlighter plugin. It's modifying the content which causes the content empty. It says in its description that it's for Gutenberg and classic editor, but it also modifies the rendered content of the cornerstone."

I can give you access to my website for you to test things and add support to it. It shouldn't be a big deal.

Regards

PS: best enlighter plugin so far for WP.

**Comment by AndiDittrich** [comment]
Hi @LIJE 

the Enlighter plugin is designed to be used with the default Wordpress editors Gutenberg and TinyMCE within the backend. it is not designed to work on the frontend or with other editors/pagebuilders.

especially the current stable version (which uses EnlighterJS v2 based on MooTools) may cause an unexpected behaviour with 3rd party javascript libraries.

the Enlighter plugin does not modify any content (with expectation of shortcodes, compatibility modes and markdown in case these options are set) - i'm not sure whats going on in your case....but i'm unable to debug the issue because the cornerstone plugin is not open source... sry

maybe you can try Enlighter v4-BETA1 but your demo page above doesn't shows any javascript errors or similar, the resources are also looking as expected.

sry!

**Comment by LIJE** [comment]
Hi,

I don't think it's related to JS issues. I think the WP plugin does something with the content.
As you said, there is no JS errors in the console. It's something else.

I know about the plugin, it's not open source but used by thousands of websites.

I can dig a bit. Which classe is parsing the content? Where should I look for it first?

**Comment by AndiDittrich** [comment]
i believe that this is a js related issue....especially any frontend editor which doesn't take care about extended native types will cause issues with MooTools.

all content filters are invoked via [ContentProcessor class](https://github.com/EnlighterJS/Plugin.WordPress/blob/v3/class/ContentProcessor.php)

the final highlighting is provided by EnlighterJS which replaces the content via js - but the related event is only invoked on page load

-----

**but first of all, try v4-BETA1 which works without MooTools**

---

you can take a look into the other support request regarding Divi oder beaver Builder for the reasons why they are not supported - i didn't earn any money with EnlighterJS nor Enlighter nor the editing plugins

without having full access to the plugin sources (including comments) and access to the final level support/developers it is impossible to add additional integrations

**Comment by LIJE** [comment]
You were right. It works with the new BETA version. Also, the code to have horizontal scrollbar changed.

Here is the new one:

`.enlighter-t-enlighter {
    width: auto !important;
    overflow-x: scroll !important;
    word-wrap: normal !important;
}

.enlighter > div {
    white-space: pre !important;
}`

**Comment by AndiDittrich** [comment]
the beta version includes a **build-in** option to control the overflow behaviour, you don't need custom css...

**Comment by LIJE** [comment]
Great. If I get a change to go to Köln, you will get a beer. I live around Strasbourg :D
