### ISSUE TITLE
Code snippet is floating to the left on the WP latest version (5.3.2) default theme Twenty Twenty. 

### ISSUE THREAD

**Issue by nahidacm** [EnlighterJS/Plugin.WordPress#228]
Frontend screenshot: https://prnt.sc/rb77cz

Admin screenshot: https://prnt.sc/rb784f

**Comment by AndiDittrich** [comment]
@nahidacm 

this issue seems to be related to the WordPress plugin and not to the Gutenberg Editor plugin.

btw. please upload your screenshots directly to GitHub as attachment next time...

------

it looks like a theme/styling issue with TwentyTwenty and not a general plugin issue - please use the element inspector in chrome/firefox to take a look into the css rules which are causing this behaviour. then you should be able to override the weak css rules.

another option is to use Enlighter v4-beta1 which is mostly immutable against such css releated issues
