### ISSUE TITLE
Code alignment error on RTL pages

### ISSUE THREAD

**Issue by arash88** [EnlighterJS/Plugin.WordPress#231]
Hi Devs,
There are huge problems where my codes get right alignment on RTL pages! but for me codes must be always be aligned at the left side of the block! also line numbers are missing!
Please consider below image, as you can see codes are aligned at right, linenumbers are missing and overall it's completely deformed!
I'm using latest stable build from Wordpress repository inside classic TinyMCE editor.

![enlighter](https://user-images.githubusercontent.com/13942180/77966441-48611800-72f8-11ea-99b7-210e11e335c9.jpg)

**Comment by AndiDittrich** [comment]
Hi @arash88 ,

the missing line numbering is caused by your theme styles which are overriding the EnlighterJS styles. you have to modify the css rules to enforce the line numbering (there is no generic solution available).

to enforce `ltr` just use the following css rule:

```css
.EnlighterJS{
    text-align: left !important;
    direction: ltr !important;
}
```

the `ltr` enforcement has been added to [EnlighterJS v3 as default](https://github.com/EnlighterJS/EnlighterJS/commit/c86be3d474373f4bba4dba4aec968f1d0aff984a)

btw. EnlighterJS has not been tested with `rtl` languages because i'm not familiar with the grammar

------

another solution for you issue: use Enlighter v4-beta1
