### ISSUE TITLE
Turn off latex syntax highlighting

### ISSUE THREAD

**Issue by rrrfer** [EnlighterJS/Plugin.WordPress#263]
Turn off latex syntax highlighting.
I am using a plugin that uses the [latex] tag to highlight formulas. After the update, all formulas became text. It's horrible...
![Снимок экрана от 2020-05-11 14-03-01](https://user-images.githubusercontent.com/21195729/81533309-2e533480-9390-11ea-8695-427cae2d662d.png)

**Comment by rrrfer** [comment]
Пока что решил проблему так: в файле enlighter/modules/core/LanguageManager.php закомментировал строку с latex. Фрагмент файла:
```
      'json' => 'JSON',
        'kotlin' => 'Kotlin',
        //'latex' => 'LaTeX',
        'less' => 'LESS',
        'lighttpd' => 'lighttpd',
        'lua' => 'LUA',
        'md' => 'Markdown',
```

Теперь все работает. Но вообще это не здорово, потому что для форматирования формул часто исопльзуется $$ a^b $$ и [latex] a^b [/latex] В первом случае формула располагается на отдельной строке, а во втором - инлайнится в текст. По крайней мере так ведет себя самый популярный в WP плагин для latex. А ваш плагин с ним конфликтует...

**Comment by AndiDittrich** [comment]
Hi @rrrfer 

**please use english or german for support request...otherwise i cannot help you.**


-----------------------

generally the shortcode editing method in WordPress (as well as in Enlighter) has been deprecated. It's recommended to use the VisualEditing modes instead to avoid a lot of issues. 

To solve your issues there a two possibilities:

1 . Disable the language shortcodes: just goto `Enlighter -> Editing -> Shortcodes -> Language shortcodes`.
2. The other "reliable" way to disable specific language shortcodes is to alter the language list via [filters](https://github.com/EnlighterJS/documentation/blob/master/wordpress/FilterHooks.md#filterenlighter_languages)

**Comment by rrrfer** [comment]
> Disable the language shortcodes: just goto Enlighter -> Editing -> Shortcodes -> Language shortcodes.

I do not see Language shortcodes. There is no such item in the interface (attached pictures)

![Снимок экрана от 2020-05-11 15-59-09](https://user-images.githubusercontent.com/21195729/81543547-68c4cd80-93a0-11ea-9539-47c22b1957f2.png)
![Снимок экрана от 2020-05-11 15-59-17](https://user-images.githubusercontent.com/21195729/81543549-69f5fa80-93a0-11ea-8eb8-6ed5829b05e7.png)

**Comment by AndiDittrich** [comment]
take a closer look... first picture, 3rd checkbox/slider
