### ISSUE TITLE
Edit code issue and Tab not working -v4.2

### ISSUE THREAD

**Issue by petr-hybler** [EnlighterJS/Plugin.WordPress#283]
Hello I am having torubles editing the exisitng code (I cannot reenter the "code editor" and have to edit directly in the post .. which is very clumsy for any copy-paste text adds lot's of mess and the formatting is crazy ....

on top of that, TAB and SHIFT+TAB is not working :( 

I am having the latest Wordpress, your plugin is v4.2 and I am running on Linux (Chrome Version 83.0.4103.116 (Official Build) (64-bit))

**Comment by AndiDittrich** [comment]
Hi @petr-hybler 

i need some more informations to help you:

* which editing mode do you use ? (tab plugin is only available for tinymce)
* did you tried another browser ?
* are there any javascript errors in the console ?
* what's exactly happening (screenshot, video) ?

i've tried to reproduce the behaviour on `Version 83.0.4103.116 (Developer Build) built on Debian 10.4, running on Debian 10.4 (64-bit)` but everything is working as expected.

currently i would assume that your issue is caused by another 3rd party plugin since both editing plugins (tinymce + gutenberg) are just based on simple text input areas and didn't take such kind of control which may block the editor.

btw. i've moved the issue into the WordPress plugin repo since it's not related to EnlighterJS
