### ISSUE TITLE
How to add a keyword for language?

### ISSUE THREAD

**Issue by GyverLibs** [EnlighterJS/Plugin.WordPress#334]
Hello! I need to add a couple of keywords to cpp language (byte, boolean, etc.). I added them to
- /resources/enlighterjs/enlighterjs.min.js
- /cache/enlighterjs.min.js
as ```...__cplusplus)\b/g,type:"e3"},{regex:/\b(\w+\d+?_t)\b/g,type:"k5"},{regex:/\b(word|boolean|byte...```
but it doesn't work.  

Also [this issue](https://github.com/EnlighterJS/Plugin.WordPress/issues/324) says that "it is possible to re-order the language list using the build-in filters". Where are these filters? Thanks

**Comment by AndiDittrich** [comment]
i wouldn't recommend to edit these files because they will be removed on each plugin update. instead enqueue your custom enlighterjs version directly.

technically you have to modify `/resources/enlighterjs/enlighterjs.min.js` and click on "save changes" on the Enlighter settings page to purge the cached files.

the mentioned filters are not related to the internal keywords - see https://github.com/EnlighterJS/documentation/blob/master/wordpress/FilterHooks.md

**Comment by GyverLibs** [comment]
thanks! It worked after "save changes"
