### ISSUE TITLE
Lines are to high

### ISSUE THREAD

**Issue by SKB-CGN** [EnlighterJS/Plugin.WordPress#339]
**Describe the bug**
Lines are to high with Colibri Theme

**WordPress Editing Mode**
Which WordPress editing mode you're using ?

* Gutenberg

**Frontend or Backend Issue**

Does the issues occurs on your frontend or on the backend (WordPress admin area)
Frontend

**To Reproduce**
?

**Expected behavior**
Normal line numbers

**Screenshots**
![2021-10-13 16_34_42-iRobot Steuerung in ioBroker - Kreyenborg koeln](https://user-images.githubusercontent.com/58603329/137154736-e93a0d9f-5962-44b7-a8c2-01c7bcd00762.png)

**Comment by StefCGN** [comment]
There are no other classes used.
![2021-10-13 16_57_13-iRobot Steuerung in ioBroker - Kreyenborg koeln](https://user-images.githubusercontent.com/58603329/137159141-d9616490-3c80-4d20-8e11-bee692e65e63.png)

**Comment by AndiDittrich** [comment]
please provide a link to your page and i'll take a short look into it

**Comment by AndiDittrich** [comment]
the Enlighter plugin is not working (other issue) because your using some kind of "optimization" plugin which adds `defer` to the script tag. see https://github.com/EnlighterJS/documentation/blob/master/wordpress/FAQ.md#javascript-error-enlighterjs-resources-not-loaded-yet for details.

it's also possible to enable the "single file mode" see `Enlighter -> options -> resources -> Initialization`

**Comment by StefCGN** [comment]
A small additional question here.
If i go to the page via my mobile phone in horizontal-mode, the code is not in a scroll-able area.
Its not scroll-able right nor left.

If i switch my phone to landscape, the code even wraps inside the area.

Is this related to the theme or to the Plugin?
