### ISSUE TITLE
Easy way to move from SyntaxHighlighter Evolved to Enlighter

### ISSUE THREAD

**Issue by SKB-CGN** [EnlighterJS/Plugin.WordPress#340]
Hi,
is there a way to perform that somehow?

**Comment by StefCGN** [comment]
What i have in the database is this:

Its a picture, because git reformats the text.
![2021-10-14 21_06_48-_neu 2 - Notepad++](https://user-images.githubusercontent.com/58603329/137380313-54dff8d3-339a-437d-a829-6cca3f903130.png)

i disabled the old one. for sure.

What i have in sourcecode is:
![2021-10-14 21_16_18-Shelly Schalter mit Xiaomi Aqara Bewegungsmelder in ioBroker schalten - Kreyenbo](https://user-images.githubusercontent.com/58603329/137381490-51912419-2075-40fa-b8f6-1edbe92d5066.png)

**Comment by StefCGN** [comment]
I am ready, when you are ;)

**Comment by AndiDittrich** [comment]
EnlighterJS Gutenberg plugin v1.2.0 includes block transformation rulesets to convert the blocks via the editor. Migration filter will follow soon

**Comment by AndiDittrich** [comment]
edit: migration filter implementation is not possible with the Gutenberg Blocks - you have to convert the posts manually - sry
