### ISSUE TITLE
Enlighter breaks new WP link dialog on front-end

### ISSUE THREAD

**Issue by EyesX** [EnlighterJS/Plugin.WordPress#35]
Enlighter breaks the new tinymce link dialog in WordPress when used on front-end. This with a thrown JS error as follows

> Uncaught TypeError: e is not a function tinymce.min.js?ver=4310-20160418:6

This does not occur when the Enlighter plugin is inactivated.

Tested with multiple themes (own theme, Twenty Fifteen, Twenty Sixteen), WordPress 4.5, 4.5.1, Enlighter 3.0, no other plugins activated.

**Comment by AndiDittrich** [comment]
Dear EyesX,

thanks for your report! i can confirm this issue - only the frontend seems to be affected. i will investigate the issue to fix it with the next release.

**Comment by AndiDittrich** [comment]
The Issue is caused by an incompatibility between **tinymce.fmt.Hooks** and **MooTools** - i think it is related to the native type extension of MooTools. The files are only loaded within the Frontend, therefore it **does not** affect the Backend.

Currently, i cannot fix this issue, because EnlighterJS 2.x requires MooTools for DOM interaction and inheritance. 

I'm working on a new EnlighterJS version which doesn't require MooTools anymore, but this will take some weeks...month to finish.

### Stacktrace (non minified version) ###

```
tinymce.min.js?ver=4310-20160418:18621 

Uncaught TypeError: hook is not a function(anonymous 
function) @ tinymce.min.js?ver=4310-20160418:18621each @ 
tinymce.min.js?ver=4310-20160418:3583postProcess @ 
tinymce.min.js?ver=4310-20160418:18620apply @ 
tinymce.min.js?ver=4310-20160418:19364addCommands.mceInsertLink @ 
tinymce.min.js?ver=4310-20160418:23624execCommand @ 
tinymce.min.js?ver=4310-20160418:22853Editor.execCommand @ 
tinymce.min.js?ver=4310-20160418:37534(anonymous function) @ 
plugin.js?wp-mce-4310-20160418:201commands.exec.(anonymous function) @ 
tinymce.min.js?ver=4310-20160418:22970execCommand @ 
tinymce.min.js?ver=4310-20160418:22853Editor.execCommand @ 
tinymce.min.js?ver=4310-20160418:37534settings.onclick @ 
tinymce.min.js?ver=4310-20160418:37359fire @ 
tinymce.min.js?ver=4310-20160418:24561proto.fire @ 
tinymce.min.js?ver=4310-20160418:26962delegate @ 
tinymce.min.js?ver=4310-20160418:27600executeHandlers @ 
tinymce.min.js?ver=4310-20160418:966defaultNativeHandler @ 
tinymce.min.js?ver=4310-20160418:993
```
