### ISSUE TITLE
Revolution Slider + Enlighter 3.1 = endless loop of exceptions

### ISSUE THREAD

**Issue by arcivanov** [EnlighterJS/Plugin.WordPress#45]
The page contains a perfectly working Slider Revolution short-code with no Enlighter short-codes. The issue occurs with or without using Autoptimizer. Only deactivating Enlighter plugin solves the problem.

These errors just proceed to accumulate at a rate of a few dozen per second. The slider itself disappears.

Uncaught TypeError: Cannot read property 'x' of undefined

computePosition @ mootools-core-yc.js?ver=4.5.3:4
setPosition @ mootools-core-yc.js?ver=4.5.3:4
j @ jquery.themepunch.tools.min.js?ver=5.2.4.1:58
n._initProps @ jquery.themepunch.tools.min.js?ver=5.2.4.1:58
n._init @ jquery.themepunch.tools.min.js?ver=5.2.4.1:58
n.render @ jquery.themepunch.tools.min.js?ver=5.2.4.1:58
n.render @ jquery.themepunch.tools.min.js?ver=5.2.4.1:58
R._updateRoot.I.render @ jquery.themepunch.tools.min.js?ver=5.2.4.1:58
n.dispatchEvent @ jquery.themepunch.tools.min.js?ver=5.2.4.1:58
v @ jquery.themepunch.tools.min.js?ver=5.2.4.1:58

**Comment by arcivanov** [comment]
Nevermind, this looks like #30, sorry for the noise.

**Comment by arcivanov** [comment]
I'm reopening this as it completely prevents me from using Enlighter with RevolutionSlider.

**Comment by arcivanov** [comment]
@bryanwillis did you solve the RevSlider issue?

**Comment by AndiDittrich** [comment]
Dear arcivanov,

i have no license for `RevolutionSlider` so it cannot test/confirm/fix this issue.

regarding to your stacktrace posted above, i believe that the issue is caused by a plugin incomaptibility between MooTools and jQuery/RevolutionSlider Tools. if its so...it is currently impossible to fix it.

i am working hard on EnlighterJS v3 which will work without an external Framework like MooTools or jQuery - this will avoid such issues in the future.

best regards, Andi

**Comment by arcivanov** [comment]
Thanks a lot!

**Comment by arcivanov** [comment]
@AndiDittrich this is the link that currently experiences problems, if this helps: https://karellen.co/239-2
