### ISSUE TITLE
How do I prevent load enlighter scripts if there is no code show in the post content.

### ISSUE THREAD

**Issue by ruikle** [EnlighterJS/Plugin.WordPress#80]
It seems all pages load MooTools JS, Enlighter CSS and JS. It's not necessary and a terrible use experience. I want to load those files only I have added code. Thanks.

**Comment by AndiDittrich** [comment]
Hi ruikle,

i understand your issue/feature request, but in most cases it doesn't matter because the static files are cached by the users webbrowser. therefore they are only downloaded once.

as a special solution, you can use the [enlighter_startup](https://github.com/AndiDittrich/WordPress.Enlighter/blob/master/docs/FilterHooks.md#filterenlighter_startup) filter to avoid Enlighter plugin initialization on selected pages. 

best regards, Andi

**Comment by ruikle** [comment]
Thanks for your quickly respond. That's a way to fix the issue. But I think it's not a perfect way.  Because: I have to frequently change the code of the filter fallback function as I add/remove posts/pages/categories.

**Comment by ruikle** [comment]
And if every plugin also adds extra CSS/JS files to all pages instead of only necessary pages. That's horrible. So I think that is a bad way. I like the Enlighter plugin. It's awesome, modern, aesthetic and powerful. So I want it better. Thanks. :)

**Comment by AndiDittrich** [comment]
i know that this is not an optimal solution...but excluding the resources from pages where the highlighting is not used is quiete difficult:

1. The JS/CSS Resources are injected into different template hooks. 
    * css: `wp_header` (before the_content) 
    * js: `wp_footer` (after the_content)

2. Enlighter can not detect if highlighting is used before `the_content` has been rendered. 

3. Enlighter Code Highlighting should work in `the_content` as well as in `comments`, `widgets`, `bb_press`, and so on. this means the current page has to be **fully rendered** to know the state (highlighting active or not). Therefore the page must be rendered in advanced to know this state - it can may be stored within the post-metadata but this won't work for `comments`, `widgets` or other elements.

4. Because of the Visual Editor Integration, the content **is not post-processed** by the plugin. Therefore an additional filter on `the_content` (as well as any other sections) would be required to detect any kind Enlighter-Code-Snippets.

It might be possible to exclude the **js** files from `wp_footer` because the content is fully populated at this time of rendering. But the **css** files cannot be excluded (populated before `the_content`). Maybe you can strip-down the css files to a single theme and include it into your WordPress Theme.

**Comment by ruikle** [comment]
Got it. I hope you can find a perfect way to fix it in the future. Congratulating for your great plugin. Thanks very much.

**Comment by BramVanroy** [comment]
I'd like to +1 this. Injecting CSS/JS when it's not necessary is bad practice.

I wonder, isn't it possible to add a hidden field (checkbox) to posts, so that when a user has code written in their post, the checkbox is checked? This way, it might be possible to hook into it in the back-end and end up with nifty stuff like this in the back-end:

```php
if ($post->isEnlighted()) {
    wp_enqueue_style(...);
    wp_enqueue_script(...);
}
```

(It's been ages since I worked with Wordpress so apologies if that does not make sense.)

It would be nice if such a getter method is public, so that themes can use it as well!

**Comment by AndiDittrich** [comment]
@BramVanroy please read my [last post](#issuecomment-323957585)

the $post object is not populated when the wp_enqueue_style hooks are invoked...therefore i cannot use this approach :(

**Comment by AndiDittrich** [comment]
@BramVanroy 
i've may found a solution but it requires an external in-memory cache like Redis... i'm not sure if this is suitable for intermediate users. additionally it won't work with caching plugins/standard CDN configs.

it's also possible to implement the "exclude footer resources" solution mentioned above. what do you think ?

**Comment by AndiDittrich** [comment]
I've added the feature to **3.6-BETA2** - available on GitHub (master branch).

The option is called "Dynamic Resource Invocation" and can be enabled under `Enlighter -> Options-> Experimental Options -> DRI` - please give it a try. 

i would appreciate your feedback

**Comment by BramVanroy** [comment]
I'll test it tonight. Is this the version that requires Redis, and won't work with other caching plugins or CDNs? These restrictions are quite cumbersome.

**Comment by AndiDittrich** [comment]
this is the "light" version which only removes the javascript files (css themes within the header are still active)

**Comment by AndiDittrich** [comment]
does it work as expected by you ?

**Comment by willstocks-tech** [comment]
Hey @AndiDittrich,

I was thinking about this earlier (obviously, as you know I’m a new Enlighter user!). What are your thoughts on:

Have a DB table specifically for Enlighter, that stores post ids where Enlighter is used and the code block themes used on that post. That way, you can ensure you enqueue only the necessary theme CSS/JS (I noticed all themes CSS is currently loaded for every page) as well as only when Enlighter is used on a page. I know it adds a DB query, but combined with a page caching plugin, the overhead should be somewhat minimal?

Might not be the most efficient option?

**Comment by AndiDittrich** [comment]
@willstocks-tech ,

thanks for your suggestion but using filters (as currently implemented) is the most efficient way to do the job. using the database adds a lot of overhead and possible cache stall conditions which are not easy to handle..

generally it's important to know which kind of users are using Enlighter and may have a benefit from "minimized resource footprint"

* **beginner**
  having a bunch of weak jquery scripts and other things on their page...optimization of Enlighter doesn't matter...
* **intermediates**
   are creating their own themes and take care of the resources - they are able to download and enqueue   EnlighterJS manually if needed
* **professional**
   using build system like `gulp` to bundle the resources

------

btw. [EnlighterJS v3](https://github.com/EnlighterJS/EnlighterJS) just needs [13kB CSS](https://github.com/EnlighterJS/EnlighterJS/blob/master/dist/enlighterjs.enlighter.min.css) (single theme) and 45kB JS (all languages, including dom lib)

**Comment by willstocks-tech** [comment]
I think you’ll find most may straddle the beginner/intermediate category (I would consider myself in the intermediate category currently, based on your definitions). I can take care of theme assets etc. But I’m not yet at the stage of using/understanding build process and systems such as gulp, grunt, webpack, wasm etc.

If you have a lot of beginner users, it’s probably best to provide as optimised a package as possible as it’s not something they may be able to look after themselves. Not only that, but they might not have implemented proper cache control!
Intermediate - again I would say as optimised a package ad possible, but with options to tweak/manage a few bits themselves
Professional - provide both optimised and unoptimised packages so that if necessary, they can optimise for their own specific use case.

As an example, I plan on only using a single theme. I _personally_ won’t use multiple themes throughout my content. If I were to use different themes (for whatever reason), I would expect that only the theme assets being used in that post would be loaded - not _all_ assets for all themes (waste of bandwidth both at my end and a users end)

58KB total package size is pretty damn nice - well done!

**Comment by AndiDittrich** [comment]
you''re not a beginner ;)
for you use-case: enqueue the EnlighterJS resources manually
