### ISSUE TITLE
Problem with X Theme

### ISSUE THREAD

**Issue by SeLoRe** [EnlighterJS/Plugin.WordPress#84]
Hi,

I use pro theme from https://theme.co/pro/  The theme has a live content builder and drag&drop builder. When I activate Enlighter plugin, live preview and drag&drop not working. My website is https://www.soruncozumu.com/

**Comment by AndiDittrich** [comment]
Hi SeLoRe,
is the issue related to the frontend or backend ?

**Comment by SeLoRe** [comment]
X builder has a frontend preview. When I choose from settings MooTools Framework Source>not include problem solving but that time enligter is not highliht codes. I have a demo website I can send you login informations.

**Comment by AndiDittrich** [comment]
This sounds like an incompatibility between your "X Theme" and the MooTools framework - therefore it is not possible to fix it in the current release. sorry!

the next major Enlighter release (v3) will work without MooTools

**Comment by SeLoRe** [comment]
What is your plan about release v3. I want use enlighter but I can't use like that also I don't want to change my highlighter plugin otherwise I have to change all codes on my website with other plugin's code snippet.

**Comment by AndiDittrich** [comment]
If there are no further problems during development, Enlighter v3 is projected to be released at the end of this year (Dec 2017).

I understand your issue but the its unable fix with the current EnlighterJS verison which depends on MooTools.

Theoretical the issue can be fixed by the Theme-Authors, because the MooTools related issues are mostly caused by some kind of bad javascript code (MooTools extends native js types).

**Comment by AndiDittrich** [comment]
@HPCIDemo 

i'm sorry but the issue with "X Pro" is related to their javascript code and the MooTools Framework used by Enlighter... it's not the plugin itself - and thats the problem...i'm unable to fix this
