### ISSUE TITLE
Autoptimize plugin compatibility

### ISSUE THREAD

**Issue by parfilov** [EnlighterJS/Plugin.WordPress#88]
Hello! There is conflict with Autoptimize plugin JS optimize option. Make them compatible please!

**Comment by AndiDittrich** [comment]
Hi Alexander,

please provide more details whats going wrong

best regards, Andi

**Comment by RobertTroughton** [comment]
Hey, I realise that Parfilov didn't put much detail into his original question - but I've seen this problem too...

Basically, if you install Autoptimize and have it optimize JS, it breaks Enlighter highlighting - so all the code simply renders in a flat (default) colour. Autoptimize is doing some "clever" stuff to try to ensure that page loads aren't stalled by JS/CSS etc.

I have Autoptimize disabled for now on my website because of this...

**Comment by AndiDittrich** [comment]
Hi Robert,

Autoptimize supports some hooks to **exclude** certain plugins/scripts from optimizing - add Enlighter and it should work

best regards, Andi
